dubbo:
  application:
    name: boot-provider
  registrys:
    protocol: zookeeper
    address: 127.0.0.1:2181
  protocol:
    name: dubbo
    port: 20880
  monitor:
    protocol: registry
server:
  port: 8050


